environment_config: {
  execution_config: {
    subnetwork_uri: "subnet-placeholder"
    authentication_config: {
        user_workload_authentication_type: END_USER_CREDENTIALS
    }
  }
}
runtime_config: {
  version: "2.2"
}
